V2
YunoHost-Apps/my_webapp_ynh pull request #107
Opened 2023-02-04 20:31 UTC by ericgaspar

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2023-02-04 20:31 UTC, ericgaspar commented
!testme

2023-02-04 22:13 UTC, ericgaspar commented
!testme

2023-02-05 09:57 UTC, alexAubin commented on tests.toml
> +    args.phpversion = "7.3"
Uuuh unfortunately we can't use `.` in the name here, though it acts as if it works, but this is equivalent to write:

```
[7]
    [7.3_test]
            only = ["install.subdir", "backup_restore", "upgrade" ]
```

with `7` being one level, and `3_test` being another level

which is not what we want :sweat_smile: 

Maybe we should rename the test to `php_73` for example or `73_test` or whatever, but without a dot :D

2023-02-05 10:51 UTC, ericgaspar commented
!testme

2023-03-03 08:41 UTC, ericgaspar commented
!testme

2023-03-28 19:59 UTC, ericgaspar commented
!testme

2023-04-05 10:37 UTC, ericgaspar commented
!testme

2023-04-05 14:22 UTC, ericgaspar commented
!testme

2023-04-11 20:26 UTC, tituspijean commented
Weirdly, the bot did not answer. Here are the badge and summary:

[![Test Badge](https://img.shields.io/endpoint?url=https://ci-apps-dev.yunohost.org/ci/api/job/6605/badge)](https://ci-apps-dev.yunohost.org/ci/job/6605)
[![](https://ci-apps-dev.yunohost.org/ci/summary/6605.png)](https://ci-apps-dev.yunohost.org/ci/job/6605)

2023-04-12 19:21 UTC, tituspijean requested changes

2023-04-12 19:21 UTC, tituspijean commented on doc/POST_INSTALL.md
> +User: __APP__
```suggestion
User: __ID__
```

2023-04-12 19:21 UTC, tituspijean commented on sources/www/index.html
>        <dd>__APP__</dd>
```suggestion
      <dd>__ID__</dd>
```

2023-04-12 19:23 UTC, tituspijean commented
(rebooting job abobe ^)

2023-04-12 20:39 UTC, ericgaspar commented
!testme

2023-05-08 12:49 UTC, closed without merging