Testing
YunoHost-Apps/my_webapp_ynh pull request #77
Opened 2022-01-10 20:20 UTC by ericgaspar

- Add PHP 7.3, 7.4 and 8.0 to choose from at install. #69
- Fix broken link

2022-01-10 20:20 UTC, ericgaspar commented
!testme

2022-01-10 20:55 UTC, yalh76 requested changes

2022-01-10 20:55 UTC, yalh76 commented on scripts/restore
> +
Shouldn't we have something like:
```
if [ $phpversion != "none" ]
then
   blablabla
fi
```

2022-01-10 20:55 UTC, yalh76 commented on scripts/restore
> +ynh_restore_file --origin_path="/etc/php/${phpversion}/fpm/pool.d/$app.conf"
Shouldn't we have something like:
```
if [ $phpversion != "none" ]
then
   blablabla
fi

2022-01-10 20:55 UTC, yalh76 commented on scripts/restore
> +ynh_systemd_action --service_name=php${phpversion}-fpm --action=reload
Shouldn't we have something like:
```
if [ $phpversion != "none" ]
then
   blablabla
fi

2022-01-11 19:14 UTC, yalh76 submitted a review, later dismissed

2022-01-11 19:14 UTC, yalh76 commented
!testme

2022-01-14 18:54 UTC, yalh76 approved these changes

2022-01-14 18:55 UTC, yalh76 commented
!testme

2022-01-15 17:18 UTC, tituspijean commented
Let's gooooo!

2022-01-15 17:18 UTC, merged

2022-01-17 14:22 UTC, kay0u reviewed
I'm sorry I'm a bit late here :X

2022-01-17 14:22 UTC, kay0u commented on scripts/install
> +    ynh_install_app_dependencies "php${phpversion}-fpm"
IIRC `ynh_add_fpm_config` will install `php${phpversion}-fpm` if needed

2022-01-17 14:22 UTC, kay0u commented on scripts/backup
> +ynh_backup --src_path="/etc/php/${phpversion}/fpm/pool.d/$app.conf"
This will probably crash if phpversion = "non"