Implement config panels v1.0
YunoHost-Apps/my_webapp_ynh pull request #94
Opened 2022-09-22 18:37 UTC by tituspijean

- [x] PHP version
- [x] PHP-FPM usage and footprint
- [x] SFTP access

Does not implement NGINX and PHP overwrite protection switches from #46.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-09-22 18:38 UTC, tituspijean commented
!testme

2022-09-23 14:49 UTC, Tagadda approved these changes
Yay 🚀

2022-09-23 15:07 UTC, ericgaspar requested changes
We need to bump version...

2022-09-23 17:32 UTC, ericgaspar approved these changes

2022-09-23 17:32 UTC, merged